# Generated by Django 3.2.8 on 2021-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreriauserapp', '0002_remove_user_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='User', max_length=100, verbose_name='Rol'),
        ),
    ]
